## * Numpy
   - numpy = numerical python 
   - majorally deals with array,however computation of stand alone values also done fastely
   - used to computation & processing of array (1D,2D .....nD array)   
   -  its a general purpose array processing package
   - it provides high dimension array packages and associated tools 

In [1]:
# installation command  >> must use before to install numpy in system
# ! pip install numpy

In [3]:
import numpy as np     # must first import to make use of it

In [5]:
# np. + tab button >> will give you different functions that supported with numpy
#(their are total 622 functions available)
len(dir(np))
                # list out objects in numpy package

622

## * array
 - homogenous data type
 - fixed dimension
 - type of the object - ndarray

#### 1)  create an array:

   * np.array() = create array
   * _arr_name_.shape  = gives shape  = gives no of rows & columns
   * _arr_name_.size  = gives total no of elements  = gives total no of elements present
   * _arr_name_.ndim  = gives dimenssions  = gives dimenssions of array
   
  

In [6]:
# create with help of list or tuple>>np.array(_list/tuple name_)
lst = [1,2,3,4,5]
print(type(lst) , lst)

<class 'list'> [1, 2, 3, 4, 5]


In [8]:
arr = np.array(lst)

# checking
print(type(arr) , arr)

# to check the shape of an array  >>i.e check no of rows and columns
arr.shape

# check the dimmenssions >> i.e 1D/2D/3D etc
arr.ndim

#trick to check dimmenssion by seeing it
# 1D array == [___values__] >> i.e only one total sqr bracket before come any value
# 2D array == [[___values__]] >> i.e total 2 sqr bracket before come any value
# 3D array == [[[___values__]]] >> i.e total 3 sqr bracket before come any value
# nD array == [[....[___values__]...]] >> i.e total 'n' sqr bracket before come any value

<class 'numpy.ndarray'> [1 2 3 4 5]


1

In [6]:
arr = np.array(range(1,11))  # all elements are 'int' only (homogeneous data) ie array
print(type(arr))
arr

#class of array is always "numpy .ndarray"

<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#  check Data type contradiction between list and array  
    # in list case
l = [2,1.4,'string',4,6]
print(type(l[-3]))
print(type(l[-1]))
print(type(l[1]))
print(type(l))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'list'>


In [10]:
# however in array case
# as array must be homogeneous but if your enter non homogeneous data types together,
# #(ie int, float ,string )python internally typecasted it to a higher level data type.
# (levels of datatype:
#        highest: string =  (called as 'object' in series case)
#                 float 
#        lower  : int)

arr = np.array([2,1.4,'string',4,6])
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['2', '1.4', 'string', '4', '6'], dtype='<U32')

In [12]:
# to check individually
print(type(arr[-3]))
print(type(arr[-1]))
print(type(arr[1]))  #everything is typecasted in higher datatype ie 'string here'


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [13]:
# float example
arr = np.array([2,1.4,4,4,6])
print(type(arr))
print(arr)

print(type(arr[-3]))
print(type(arr[-1]))

<class 'numpy.ndarray'>
[2.  1.4 4.  4.  6. ]
<class 'numpy.float64'>
<class 'numpy.float64'>


#### difference between list and array
#### differance array vs list

   * arr = [ 2  4  6  8 10 12 14 16 18 20 ]
   * lst =  [2,4,6,8,10,12,14,16,18,20,]
   * list is one type of array, but numpy is written in C code  and which is fast and optimised which comes with so many functionality if we compare vs list
   


####        List                                         |                               Array
    - support non homogeneous data                   |    - support non homogeneous data 
    - broadcasting is not supported                  |    - broadcasting is supported
     (direct operation with elements in list)  
    - take more memory                               |    -  take less memory
    - comparatively poor in arithmatic operations    |    - since rich in functionality widely use for arithmatic oprations
    - no need to declare in advance                  |    - need to declare in advance(importing library)

In [17]:
### with List

list_ = list(range(1,21))
print(list_)
print (list_* 2 )  # *(astric sign) with list appends duplicate list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [19]:
###  '*' with Array
arr = np.array(list_)
print(arr*2)  # *(astric sign) with array gives element-wise multiplication

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [20]:
###  '+' with Array
arr1 = np.array(list_)
arr2 = np.array(list_)
print(arr1)
print(arr2)
print(arr1+arr2) # +(plus sign) with array gives element-wise addition

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


## * various ways of creating array object

    - 'np.+tab' >> will give you different functions that supported with numpy(their are Ttotal 622 functions available)

##### 1)  np.empty gives defined(1d or 2d or 3d) array filled with junk(garbage) values

In [10]:
#1)  .empty gives defined(1d or 2d or 3d) array filled with junk(garbage) values

#1d array:shape = (columns)
arr = np.empty(shape = 5)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[7.65109550e-312 7.65126905e-312 7.65123826e-312 7.65126897e-312
 7.65126904e-312]


In [23]:
#2d array:shape = (rows, columns)

arr = np.empty(shape = (2,4))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 6.8378685e-321, 8.4560344e-307, 1.2461147e-306]])

In [25]:
#3d array:shape = (rows, columns,depth/set in each row)
arr = np.empty(shape = (2,3,4))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.60219442e-306],
        [2.22523004e-307, 1.78020440e-306, 3.11525958e-307,
         3.33774999e-307],
        [6.23050898e-307, 1.06811422e-306, 1.78018403e-306,
         1.60220393e-306]],

       [[1.02359984e-306, 6.23056330e-307, 4.45057212e-308,
         1.20160847e-306],
        [1.33506604e-306, 2.22522597e-306, 8.90104239e-307,
         1.60219035e-306],
        [6.23059726e-307, 1.20161458e-306, 1.33512512e-306,
         1.23971654e+224]]])

##### 2)  np.zeroes gives defined(1d or 2d or 3d) array filled all with value zero('0')

In [18]:
##1d
arr = np.zeros(shape = 5)
print(type(arr))
print(arr)

print('\n')

##2d
arr = np.zeros(shape = (2,3))
print(type(arr))
print(arr)

#3rd:zero_likes : take previous shape and size only element values replaces with zeros
print('\n')
arr1 = np.zeros_like(arr)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]


<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]


<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]


##### 3)  np.ones gives defined(1d or 2d or 3d) array filled all with value one('1')

In [32]:
##1d
arr = np.ones(shape = 5)
print(type(arr))
print(arr)

print('\n\n')

##2d
arr = np.ones(shape = (2,3),dtype = 'int') #we can define datatype on our desire
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]



<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]]


##### 3A)  np.eye gives identity matrix .ie matrix which has all its diagonal elemet =1,all other elemnt =0

In [21]:
arr = np.eye(5)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
arr = np.eye(3)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 4) np .linespace (start= ,stop= ,num=  ): 
   - creates arrray from value given in 'start' (its a min value of array) to the value given in'stop' (its a max value of array),with 'num' is total equal intervals in between
   - where total numbers of values in array is given in num

In [33]:
##
arr = np.linspace(start = 1, stop = 10, num = 20)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

##### 5)  .arange (start= ,stop= ,step=  ): 
    -same as line space just insted of num here its step which provides stepsize i.e (differance between two consecutive values)

In [13]:
##
arr = np.arange(start = 1, stop = 10, step = 2)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

In [12]:
# we can creat it without stepsize too
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

##### 6)  np.random.---- ( ):  
    -random. has again numerous function like(random.randint,random.rand,random.randin etc etc)
    which fills array with random values however creation of array is basically depends upoun last .function 

In [36]:
##np.random.randint = (low =lowest value ,high = highest value,size = total )no of elements in an array
#sequence i array is always random

#for 1d
arr = np.random.randint(low = 2, high = 5, size = 20)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([3, 2, 2, 2, 4, 2, 3, 3, 4, 2, 2, 4, 4, 2, 2, 4, 3, 4, 2, 4])

In [37]:
# for 2d
arr = np.random.randint(low = 2, high = 5, size = (5,2))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[4, 2],
       [3, 3],
       [3, 4],
       [4, 2],
       [2, 3]])

In [38]:
##np.random.rand = ( )Create an array of the given shape and populate it with
#random samples from a uniform distribution

arr = np.random.rand(5,2)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.43896046, 0.09916084],
       [0.2283106 , 0.25263189],
       [0.37198766, 0.85182167],
       [0.28372527, 0.57789216],
       [0.58791824, 0.9577879 ]])

In [39]:
arr = np.random.randn(5,2)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[ 0.46748364,  0.91296269],
       [-1.26766346,  0.2518621 ],
       [ 0.00825996, -0.36144063],
       [ 1.34433144,  1.00304739],
       [-0.82456858,  0.7553219 ]])

## Acceessing array elements

In [40]:
##
arr = np.arange(start = 1, stop = 20, step = 2)
print(type(arr))
print(len(arr))
arr

<class 'numpy.ndarray'>
10


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
arr1 = arr.reshape(2,5)      #reshape is used to change the dimensions
arr1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [42]:
## fetch element '5'
print(arr1[0,2])
print(arr1[0][2])

5
5


In [43]:
## fetch element '17'
print(arr1[1,3])
print(arr1[1][3])

17
17


In [48]:
   #unlike list in array it directly performs arithmatic opearation with element
### 
print(arr1)
print('\n')
print(arr1 + 1)
print('\n')
print(arr1 * 2) # element-wise multiplication

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


[[ 2  4  6  8 10]
 [12 14 16 18 20]]


[[ 2  6 10 14 18]
 [22 26 30 34 38]]


In [49]:
# dot product >>matrix multiplication
# matrix multiplication

arr1 = np.arange(start = 1, stop = 20, step = 2).reshape(5,2)
arr2 = np.arange(start = 3, stop = 23, step = 2).reshape(2,5)
print(arr1)
print('\n')
print(arr2)

arr1.dot(arr2) # matrix multiplication

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


[[ 3  5  7  9 11]
 [13 15 17 19 21]]


array([[ 42,  50,  58,  66,  74],
       [106, 130, 154, 178, 202],
       [170, 210, 250, 290, 330],
       [234, 290, 346, 402, 458],
       [298, 370, 442, 514, 586]])

In [50]:
# element-wise multiplication

arr1 = np.arange(start = 1, stop = 20, step = 2)
arr2 = np.arange(start = 3, stop = 23, step = 2)
print(arr1)
print('\n')
print(arr2)
arr1*arr2 # element-wise multiplication

[ 1  3  5  7  9 11 13 15 17 19]


[ 3  5  7  9 11 13 15 17 19 21]


array([  3,  15,  35,  63,  99, 143, 195, 255, 323, 399])

In [23]:
ls


 Volume in drive H is study
 Volume Serial Number is BA01-0E95

 Directory of H:\LEARNBAY\my notes\python

27-05-2021  19:46    <DIR>          .
27-05-2021  19:46    <DIR>          ..
27-05-2021  18:52    <DIR>          .ipynb_checkpoints
23-05-2021  09:14    <DIR>          __pycache__
26-05-2021  19:13           157,369 assignment.ipynb
27-05-2021  19:26           271,112 class_17_Numpy by afsaan.ipynb
23-05-2021  20:40                61 file.txt
22-05-2021  19:53           920,464 Git and Github.ipynb
04-05-2020  09:33             5,453 IMP Extra Concept.ipynb
23-05-2021  23:13            30,722 iterables & file handlling part 3.ipynb
22-05-2021  17:20            75,133 My python notebook part 1.ipynb
23-05-2021  00:54            34,325 My python notebook part 2.ipynb
23-05-2021  22:58                19 my_mod.py
23-05-2021  22:45                 0 my_mod_1.py
23-05-2021  22:46                 0 my_mod_2.py
23-05-2021  22:49                15 my_mod_3.py
27-05-2021  19:46            