In [1]:
"""

.      - Any character Except new
\d     - Digit(0-9)
\D     - Not a digit(0-9)
\w     - Word character (a-z , A-Z , 0-9 , _)
\W     - not a word charcter
\s     - whitespaces ( spaces , tab , newline)
\S     - not whitespaces 


\b - Word boundry
\B - not a word boundry
^ - begining of the string
$ - End of the string


[] - matchers character in brackets
[^ ] - match character not in the bracket
|  - Either or
() - Group


Qunatifiers:
* - 0 or more
+ - 1 or more
? - 0 or one
{3} - Exact number
{3,4} - range of number { min , max}



"""

'\n\n.      - Any character Except new\n\\d     - Digit(0-9)\n\\D     - Not a digit(0-9)\n\\w     - Word character (a-z , A-Z , 0-9 , _)\n\\W     - not a word charcter\n\\s     - whitespaces ( spaces , tab , newline)\n\\S     - not whitespaces \n\n\n\x08 - Word boundry\n\\B - not a word boundry\n^ - begining of the string\n$ - Endof the string\n\n\n[] - matchers character in brackets\n[^ ] - match character not in the bracket\n|  - Either or\n() - Group\n\n\nQunatifiers:\n* - 0 or more\n+ - 1 or more\n? - 0 or one\n{3} - Exact number\n{3,4} - range of number { min , max}\n\n\n\n'

In [4]:
text_to_search = '''abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan11.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [5]:
import re

In [6]:
pattern = re.compile('abc')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='abc'>


In [7]:
print(text_to_search[0:3])

abc


In [8]:
#Dot(.)
pattern = re.compile('.')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(2, 3), match='c'>
<re.Match object; span=(3, 4), match='d'>
<re.Match object; span=(4, 5), match='e'>
<re.Match object; span=(5, 6), match='f'>
<re.Match object; span=(6, 7), match='g'>
<re.Match object; span=(7, 8), match='h'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(9, 10), match='j'>
<re.Match object; span=(10, 11), match='k'>
<re.Match object; span=(11, 12), match='l'>
<re.Match object; span=(12, 13), match='m'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(15, 16), match='p'>
<re.Match object; span=(16, 17), match='q'>
<re.Match object; span=(17, 18), match='u'>
<re.Match object; span=(18, 19), match='r'>
<re.Match object; span=(19, 20), match='t'>
<re.Match object; span=(20, 21), match='u'>
<re.Match object; span=(21, 22), match='v'>
<re.Match object; span=(22, 23), match='w'>
<re.Mat

In [9]:
#\d(0-9)
pattern = re.compile('\d')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(56, 57), match='3'>
<re.Match object; span=(57, 58), match='2'>
<re.Match object; span=(58, 59), match='1'>
<re.Match object; span=(60, 61), match='5'>
<re.Match object; span=(61, 62), match='5'>
<re.Match object; span=(62, 63), match='5'>
<re.Match object; span=(64, 65), match='4'>
<re.Match object; span=(65, 66), match='3'>
<re.Match object; span=(66, 67), match='2'>
<re.Match object; span=(67, 68), match='1'>
<re.Match object; span=(69, 70), match='1'>
<re.Match object; span=(70, 71), match='2'>
<re.Match object; span=(71, 72), match='3'>
<re.Match object; span=(72, 73), match='4'>
<re.Match object; span=(73, 74), match='5'>
<re.Match object; span=(74, 75), match='6'>
<re.Match object; span=(75, 76), match='7'>
<re.Match object; span=(76, 77), match='8'>
<re.Match object; span=(77, 78), match='9'>
<re.Match object; span=(78, 79), match='0'>
<re.Match object; span=(163, 164), match='1'>
<re.Match object; span=(164, 165), match='1'>
<re.Match object; span=(170,

In [11]:
#\D everthing except (0-9)
pattern = re.compile('\D')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(2, 3), match='c'>
<re.Match object; span=(3, 4), match='d'>
<re.Match object; span=(4, 5), match='e'>
<re.Match object; span=(5, 6), match='f'>
<re.Match object; span=(6, 7), match='g'>
<re.Match object; span=(7, 8), match='h'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(9, 10), match='j'>
<re.Match object; span=(10, 11), match='k'>
<re.Match object; span=(11, 12), match='l'>
<re.Match object; span=(12, 13), match='m'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(15, 16), match='p'>
<re.Match object; span=(16, 17), match='q'>
<re.Match object; span=(17, 18), match='u'>
<re.Match object; span=(18, 19), match='r'>
<re.Match object; span=(19, 20), match='t'>
<re.Match object; span=(20, 21), match='u'>
<re.Match object; span=(21, 22), match='v'>
<re.Match object; span=(22, 23), match='w'>
<re.Mat

In [12]:
#\w Word character 
pattern = re.compile('\w')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(2, 3), match='c'>
<re.Match object; span=(3, 4), match='d'>
<re.Match object; span=(4, 5), match='e'>
<re.Match object; span=(5, 6), match='f'>
<re.Match object; span=(6, 7), match='g'>
<re.Match object; span=(7, 8), match='h'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(9, 10), match='j'>
<re.Match object; span=(10, 11), match='k'>
<re.Match object; span=(11, 12), match='l'>
<re.Match object; span=(12, 13), match='m'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(15, 16), match='p'>
<re.Match object; span=(16, 17), match='q'>
<re.Match object; span=(17, 18), match='u'>
<re.Match object; span=(18, 19), match='r'>
<re.Match object; span=(19, 20), match='t'>
<re.Match object; span=(20, 21), match='u'>
<re.Match object; span=(21, 22), match='v'>
<re.Match object; span=(22, 23), match='w'>
<re.Mat

In [14]:
#\W  not Word character 
pattern = re.compile('\W')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(26, 27), match='\n'>
<re.Match object; span=(53, 54), match='\\'>
<re.Match object; span=(55, 56), match='\n'>
<re.Match object; span=(59, 60), match='-'>
<re.Match object; span=(63, 64), match='-'>
<re.Match object; span=(68, 69), match='\n'>
<re.Match object; span=(79, 80), match='\n'>
<re.Match object; span=(82, 83), match=' '>
<re.Match object; span=(87, 88), match='\n'>
<re.Match object; span=(102, 103), match=' '>
<re.Match object; span=(103, 104), match='('>
<re.Match object; span=(108, 109), match=' '>
<re.Match object; span=(111, 112), match=' '>
<re.Match object; span=(114, 115), match=' '>
<re.Match object; span=(122, 123), match=')'>
<re.Match object; span=(123, 124), match=':'>
<re.Match object; span=(124, 125), match='\n'>
<re.Match object; span=(125, 126), match='.'>
<re.Match object; span=(126, 127), match=' '>
<re.Match object; span=(127, 128), match='^'>
<re.Match object; span=(128, 129), match=' '>
<re.Match object; span=(129, 130), match='$'>

In [15]:
# \s - whitespace(space , tab . newline)

pattern = re.compile('\s')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(26, 27), match='\n'>
<re.Match object; span=(55, 56), match='\n'>
<re.Match object; span=(68, 69), match='\n'>
<re.Match object; span=(79, 80), match='\n'>
<re.Match object; span=(82, 83), match=' '>
<re.Match object; span=(87, 88), match='\n'>
<re.Match object; span=(102, 103), match=' '>
<re.Match object; span=(108, 109), match=' '>
<re.Match object; span=(111, 112), match=' '>
<re.Match object; span=(114, 115), match=' '>
<re.Match object; span=(124, 125), match='\n'>
<re.Match object; span=(126, 127), match=' '>
<re.Match object; span=(128, 129), match=' '>
<re.Match object; span=(130, 131), match=' '>
<re.Match object; span=(132, 133), match=' '>
<re.Match object; span=(134, 135), match=' '>
<re.Match object; span=(136, 137), match=' '>
<re.Match object; span=(138, 139), match=' '>
<re.Match object; span=(140, 141), match=' '>
<re.Match object; span=(142, 143), match=' '>
<re.Match object; span=(144, 145), match=' '>
<re.Match object; span=(146, 147), match

In [17]:
#\S - not whitespace(space , tab . newline)

pattern = re.compile('\S')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(2, 3), match='c'>
<re.Match object; span=(3, 4), match='d'>
<re.Match object; span=(4, 5), match='e'>
<re.Match object; span=(5, 6), match='f'>
<re.Match object; span=(6, 7), match='g'>
<re.Match object; span=(7, 8), match='h'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(9, 10), match='j'>
<re.Match object; span=(10, 11), match='k'>
<re.Match object; span=(11, 12), match='l'>
<re.Match object; span=(12, 13), match='m'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(15, 16), match='p'>
<re.Match object; span=(16, 17), match='q'>
<re.Match object; span=(17, 18), match='u'>
<re.Match object; span=(18, 19), match='r'>
<re.Match object; span=(19, 20), match='t'>
<re.Match object; span=(20, 21), match='u'>
<re.Match object; span=(21, 22), match='v'>
<re.Match object; span=(22, 23), match='w'>
<re.Mat

In [18]:
# \b -- boundry

string = 'cat catherine catholic wildcat copycat uncathable'

pattern = re.compile(r'cat')

matches = pattern.finditer(string)

for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(4, 7), match='cat'>
<re.Match object; span=(14, 17), match='cat'>
<re.Match object; span=(27, 30), match='cat'>
<re.Match object; span=(35, 38), match='cat'>
<re.Match object; span=(41, 44), match='cat'>


In [19]:
string = 'cat catherine catholic wildcat copycat uncathable'

pattern = re.compile('cat ')

matches = pattern.finditer(string)

for match in matches:
    print(match)

<re.Match object; span=(0, 4), match='cat '>
<re.Match object; span=(27, 31), match='cat '>
<re.Match object; span=(35, 39), match='cat '>


In [22]:
string = 'cat catherine catholic wildcat copycat uncathable'

pattern = re.compile(r'\bcat\b')

matches = pattern.finditer(string)

for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='cat'>


In [ ]:
# string = 'cat catherine catholic wildcat copycat uncathable'

# pattern = re.compile(r'\bcat\b')

# matches = pattern.finditer(string)

# for match in matches:
#     print(match)

In [26]:
string_1 = 'she sells seashells'

pattern = re.compile(r'\bs\b')

matches = pattern.finditer(string_1)

for match in matches:
    print(match)

In [29]:
# \B not a word boundry

string_1 = 'she sells seashells sea'

pattern = re.compile(r'sea')

matches = pattern.finditer(string_1)

for match in matches:
    print(match)

<re.Match object; span=(10, 13), match='sea'>
<re.Match object; span=(20, 23), match='sea'>


In [32]:
# ^ - beggining of the string


string_1 = 'she sells seashells sea'

pattern = re.compile(r'^se')

matches = pattern.finditer(string_1)

for match in matches:
    print(match)

In [34]:
#$ - end of the string


string_1 = 'she sells seashells sea'

pattern = re.compile(r'sea$')

matches = pattern.finditer(string_1)

for match in matches:
    print(match)

<re.Match object; span=(20, 23), match='sea'>


In [45]:
text_to_search = '''abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan11.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
900 555 1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

pattern = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(84, 96), match='555-555-1234'>
<re.Match object; span=(199, 211), match='321-555-4321'>
<re.Match object; span=(252, 264), match='800-555-1234'>
<re.Match object; span=(265, 277), match='900-555-1234'>


In [47]:
f = open('regex_data.txt')
file_text = f.read()
f.close()

pattern = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
matches = pattern.finditer(file_text)
for i in matches:
    print(i)

<re.Match object; span=(12, 24), match='615-555-7164'>
<re.Match object; span=(102, 114), match='800-555-5669'>
<re.Match object; span=(191, 203), match='560-555-5153'>
<re.Match object; span=(281, 293), match='900-555-9340'>
<re.Match object; span=(378, 390), match='714-555-7405'>
<re.Match object; span=(467, 479), match='800-555-6771'>
<re.Match object; span=(557, 569), match='783-555-4799'>
<re.Match object; span=(647, 659), match='516-555-4615'>
<re.Match object; span=(740, 752), match='127-555-1867'>
<re.Match object; span=(829, 841), match='608-555-4938'>
<re.Match object; span=(915, 927), match='568-555-6051'>
<re.Match object; span=(1003, 1015), match='292-555-1875'>
<re.Match object; span=(1091, 1103), match='900-555-3205'>
<re.Match object; span=(1180, 1192), match='614-555-1166'>
<re.Match object; span=(1269, 1281), match='530-555-2676'>
<re.Match object; span=(1355, 1367), match='470-555-2750'>
<re.Match object; span=(1439, 1451), match='800-555-6089'>
<re.Match object; spa

In [50]:
text_to_search = '''abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan11.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
900-555.1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''


pattern = re.compile(r'\d\d\d.\d\d\d.\d\d\d\d')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(56, 68), match='321-555-4321'>
<re.Match object; span=(170, 182), match='321-555-4321'>
<re.Match object; span=(183, 195), match='123.555.1234'>
<re.Match object; span=(210, 222), match='123.555.1234'>
<re.Match object; span=(223, 235), match='800-555-1234'>
<re.Match object; span=(236, 248), match='900-555-1234'>
<re.Match object; span=(249, 261), match='900 555 1234'>


In [52]:
# [] = matches character inside a bracket

text_to_search = '''abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan11.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
900-555.1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''


pattern = re.compile(r'\d\d\d[-.]\d\d\d[-.]\d\d\d\d')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(56, 68), match='321-555-4321'>
<re.Match object; span=(170, 182), match='321-555-4321'>
<re.Match object; span=(183, 195), match='123.555.1234'>
<re.Match object; span=(210, 222), match='123.555.1234'>
<re.Match object; span=(223, 235), match='800-555-1234'>
<re.Match object; span=(236, 248), match='900-555-1234'>
<re.Match object; span=(249, 261), match='900-555.1234'>


In [54]:
# Q4 - match only those phone number which starts with 800 or 900


# anwer 1
pattern=re.compile(r'[89]00[-.]\d\d\d[-.]\d\d\d\d\b') 

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(223, 235), match='800-555-1234'>
<re.Match object; span=(236, 248), match='900-555-1234'>
<re.Match object; span=(249, 261), match='900-555.1234'>


In [55]:
#

pattern = re.compile(r'(800|900)[-.]\d\d\d[-.]\d\d\d\d') 

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(223, 235), match='800-555-1234'>
<re.Match object; span=(236, 248), match='900-555-1234'>
<re.Match object; span=(249, 261), match='900-555.1234'>


In [60]:
pattern = re.compile(r'[1-5A-Z]') 

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(27, 28), match='A'>
<re.Match object; span=(28, 29), match='B'>
<re.Match object; span=(29, 30), match='C'>
<re.Match object; span=(30, 31), match='D'>
<re.Match object; span=(31, 32), match='E'>
<re.Match object; span=(32, 33), match='F'>
<re.Match object; span=(33, 34), match='G'>
<re.Match object; span=(34, 35), match='H'>
<re.Match object; span=(35, 36), match='I'>
<re.Match object; span=(36, 37), match='J'>
<re.Match object; span=(37, 38), match='K'>
<re.Match object; span=(38, 39), match='L'>
<re.Match object; span=(39, 40), match='M'>
<re.Match object; span=(40, 41), match='N'>
<re.Match object; span=(41, 42), match='O'>
<re.Match object; span=(42, 43), match='P'>
<re.Match object; span=(43, 44), match='Q'>
<re.Match object; span=(44, 45), match='R'>
<re.Match object; span=(45, 46), match='S'>
<re.Match object; span=(46, 47), match='T'>
<re.Match object; span=(47, 48), match='U'>
<re.Match object; span=(48, 49), match='V'>
<re.Match object; span=(49, 50),

In [61]:
# [^ ] - match character not in the bracket

pattern = re.compile(r'[^1-5A-Z]') 

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(2, 3), match='c'>
<re.Match object; span=(3, 4), match='d'>
<re.Match object; span=(4, 5), match='e'>
<re.Match object; span=(5, 6), match='f'>
<re.Match object; span=(6, 7), match='g'>
<re.Match object; span=(7, 8), match='h'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(9, 10), match='j'>
<re.Match object; span=(10, 11), match='k'>
<re.Match object; span=(11, 12), match='l'>
<re.Match object; span=(12, 13), match='m'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(15, 16), match='p'>
<re.Match object; span=(16, 17), match='q'>
<re.Match object; span=(17, 18), match='u'>
<re.Match object; span=(18, 19), match='r'>
<re.Match object; span=(19, 20), match='t'>
<re.Match object; span=(20, 21), match='u'>
<re.Match object; span=(21, 22), match='v'>
<re.Match object; span=(22, 23), match='w'>
<re.Mat

In [63]:
# question -- extract everything except bat

# student 1 - not feasible
pattern = re.compile(r'cat|fat|mat') 

matches = pattern.finditer(t'cat fat mat bat')

for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(4, 7), match='fat'>
<re.Match object; span=(8, 11), match='mat'>


In [67]:
# not correct

pattern = re.compile(r'[^bat]') 

matches = pattern.finditer('cat fat mat bat')

for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='c'>
<re.Match object; span=(3, 4), match=' '>
<re.Match object; span=(4, 5), match='f'>
<re.Match object; span=(7, 8), match=' '>
<re.Match object; span=(8, 9), match='m'>
<re.Match object; span=(11, 12), match=' '>


In [72]:
# one of the correct answer

pattern = re.compile(r'bat') 

matches = pattern.finditer('cat fat mat bat')

for match in matches:
    print(match)

<re.Match object; span=(1, 4), match='at '>
<re.Match object; span=(5, 8), match='at '>
<re.Match object; span=(9, 12), match='at '>


In [ ]:
# Q2 . what if we only want to exclude bat

pattern = re.compile(r'bat') 

matches = pattern.finditer('cat fat mat bat')

for match in matches:
    print(match)

In [75]:
# for multiple maytching we use something qunatifiers


pattern = re.compile(r'\d{3,4}[-.]\d{3,4}[-.]\d{3,4}')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(56, 68), match='321-555-4321'>
<re.Match object; span=(170, 182), match='321-555-4321'>
<re.Match object; span=(183, 195), match='123.555.1234'>
<re.Match object; span=(210, 222), match='123.555.1234'>
<re.Match object; span=(223, 235), match='800-555-1234'>
<re.Match object; span=(236, 248), match='900-555-1234'>
<re.Match object; span=(249, 261), match='900-555.1234'>


In [ ]:
text_to_search = '''abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan11.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
900-555.1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr. 
Mr_hello
'''

In [76]:
pattern = re.compile(r'Mr')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 264), match='Mr'>
<re.Match object; span=(274, 276), match='Mr'>
<re.Match object; span=(292, 294), match='Mr'>
<re.Match object; span=(306, 308), match='Mr'>
<re.Match object; span=(312, 314), match='Mr'>


In [77]:
pattern = re.compile(r'Mr\.')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 265), match='Mr.'>
<re.Match object; span=(306, 309), match='Mr.'>


In [78]:
pattern = re.compile(r'Mr\.\s')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 266), match='Mr. '>
<re.Match object; span=(306, 310), match='Mr. '>


In [80]:
pattern = re.compile(r'Mr\.\s[A-z]\w\w\w\w\w\w')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 273), match='Mr. Schafer'>


In [81]:
+ - 1 or more

pattern = re.compile(r'Mr\.\s[A-z]\w+')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 273), match='Mr. Schafer'>


In [82]:
pattern = re.compile(r'Mr\.\s[A-z]\w*')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 273), match='Mr. Schafer'>
<re.Match object; span=(306, 311), match='Mr. T'>


In [84]:
pattern = re.compile(r'M[rs]\.?\s[A-z]\w*')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 273), match='Mr. Schafer'>
<re.Match object; span=(274, 282), match='Mr Smith'>
<re.Match object; span=(283, 291), match='Ms Davis'>
<re.Match object; span=(306, 311), match='Mr. T'>


In [91]:
pattern = re.compile(r'M(rs|r|s)\.?\s\w+')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(262, 273), match='Mr. Schafer'>
<re.Match object; span=(274, 282), match='Mr Smith'>
<re.Match object; span=(283, 291), match='Ms Davis'>
<re.Match object; span=(292, 305), match='Mrs. Robinson'>
<re.Match object; span=(306, 311), match='Mr. T'>


In [90]:
# () group

pattern = re.compile(r'(Sc|Sm|Da)')

matches = pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(1, 2), match='b'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(13, 14), match='n'>
<re.Match object; span=(14, 15), match='o'>
<re.Match object; span=(44, 45), match='R'>
<re.Match object; span=(54, 55), match='s'>
<re.Match object; span=(101, 102), match='s'>
<re.Match object; span=(103, 104), match='('>
<re.Match object; span=(110, 111), match='o'>
<re.Match object; span=(112, 113), match='b'>
<re.Match object; span=(116, 117), match='s'>
<re.Match object; span=(122, 123), match=')'>
<re.Match object; span=(149, 150), match='('>
<re.Match object; span=(151, 152), match=')'>
<re.Match object; span=(156, 157), match='n'>
<re.Match object; span=(159, 160), match='s'>
<re.Match object; span=(162, 163), match='n'>
<re.Match object; span=(167, 168), match='o'>
<re.Match object; span=(279, 280), match='i'>
<re.Match object; span=(284, 285), match='s'>
<re.Match object; span=(289, 290), match='i'>
<re.Match object; span=(290, 291), match='s'>
<re.

In [93]:
emails = '''
AfsanMKhan@gmail.com     # valid
afsan.khan@university.edu  #valid
afsan-321-khan@my-work.net  #valid
afsan-321-khan@my-work.abc  # not valid
'''

In [95]:
pattern = re.compile(r'[a-zA-Z0-9-.]+@[a-z-]+\.(edu|net|com)')

matches = pattern.finditer(emails)

for match in matches:
    print(match)

<re.Match object; span=(1, 21), match='AfsanMKhan@gmail.com'>
<re.Match object; span=(34, 59), match='afsan.khan@university.edu'>
<re.Match object; span=(68, 94), match='afsan-321-khan@my-work.net'>


# NUMPY

In [ ]:
# numpy - Numerical- num python -py

# numpy - fast computation and procession of a 1d or ndim arrays

# numpy is written in c
# - fast
# - optimised

In [96]:
!pip install numpy


# https://pypi.org/project/numpy/  - to install any library

In [97]:
# how to create a numpy array

In [100]:
import numpy as np

In [98]:
# 1. can be created with the help of list or tuples
lst = [1,2,3,4,5]
print(type(lst) , lst)

<class 'list'> [1, 2, 3, 4, 5]


In [103]:
arr = np.array(lst)

# checking
print(type(arr) , arr)

# to check the shape of an array
arr.shape

# check the dim
arr.ndim

<class 'numpy.ndarray'> [1 2 3 4 5]


1

In [115]:
lst = [[1,2,3,4,5] , [5,6,7,8,9]]
print(type(lst) , lst)

<class 'list'> [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]


In [116]:
arr_1 = np.array(lst)

# checking
print(type(arr_1) , arr_1)

# to check the shape of an array
arr_1.shape

# # check the dim
arr_1.ndim

<class 'numpy.ndarray'> [[1 2 3 4 5]
 [5 6 7 8 9]]


2

In [117]:
# how many elmenst are der in array
arr_1.size

10

In [118]:
arr_1.shape

(2, 5)

In [119]:
# 2 - arange

np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [121]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [122]:
np.arange(1 , 8 , -1) # contradiction

array([], dtype=int64)

In [126]:
# 3 -linespace

np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [127]:
np.linspace(1,100,200)

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34